//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstTry
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class storage_using
    {
        public int id { get; set; }

        [Display(Name = "Лікар")]
        public int doctor_id { get; set; }

        [Display(Name = "Предмет")]
        public int item_id { get; set; }

        [Display(Name = "Кількість")]
        public int count { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Display(Name = "Дата")]
        public System.DateTime date { get; set; }
    
        public virtual doctors doctors { get; set; }
        public virtual storage storage { get; set; }
    }
}
